from helper import debug
from settings import SINCE, TIME_ZONE, UNTIL
from timewindow import duration, during_off_hours, during_peak_sleep

import datetime


def count_incident_type(incidents, type):
    """
    Gets total number of incidents of a certain type

    :param incidents: dictionary -- set of incidents to parse
    :param type: string -- key to parse within incidents
    :return: int -- total incidents
    """

    total = 0

    for _, incident in incidents.items():
        total += incident[type]

    return total


def init_incident(incident):
    """
    Initializes an incident hash.

    :param incident: dictionary -- incident object generated by pygerduty.incidents()
    :return dictionary -- initialized incident hash
    """

    return {
        'urgency': incident.urgency,
        'total_duration': datetime.timedelta(),
        'total_incidents': 0,
        'off_hours': 0,
        'peak_sleep': 0
    }


def collate_incidents(pagerduty, since=SINCE, until=UNTIL, time_zone=TIME_ZONE):
    """
    Parses incidents from the PagerDuty API, collects them into groups based on
    the incident type, and generates metrics for each incident group.

    :param pagerduty: PagerDuty -- established connection to the PagerDuty API
    :param since: string in ISO 8601 combined datetime format -- the start of the reporting window
    :param until: string in ISO 8601 combined datetime format -- the end of the reporting window
    :param time_zone: string in IANA time zone database format -- timezone of the reporting window
    :return dictionary -- collected incidents with associated metrics
    """
    incidents = {}
    for incident in pagerduty.incidents.list(since=since, until=until, time_zone=time_zone):
        debug('New "{incident}" incident!'.format(incident=incident.title))

        if incident.title not in incidents:
            incidents[incident.title] = init_incident(incident)

        incidents[incident.title]['total_duration'] += duration(incident)
        debug('Total duration to ' + str(incidents[incident.title]['total_duration']), 2)

        incidents[incident.title]['total_incidents'] += 1
        debug('Total incidents to ' + str(incidents[incident.title]['total_incidents']), 2)

        if during_off_hours(incident):
            incidents[incident.title]['off_hours'] += 1

        if during_peak_sleep(incident):
            incidents[incident.title]['peak_sleep'] += 1

        debug()

    return incidents
